#!/bin/sh
#

export PATH=/sbin:/bin:/usr/sbin:/usr/bin
export TERM=linux
NEWROOT="/sysroot"

RDDEBUG=""
. /lib/dracut-lib.sh

mknod -m 0666 /dev/null c 1 3

mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo "Mounting debugfs"
mount -t debugfs debugfs /sys/kernel/debug
if [ -f /sys/kernel/debug/x86/ibrs_enabled ]; then
    echo "Current IBRS Setting is $(cat /sys/kernel/debug/x86/ibrs_enabled)"
    echo "Disabling IBRS"
    echo 0 > /sys/kernel/debug/x86/ibrs_enabled
    echo "New IBRS Setting is $(cat /sys/kernel/debug/x86/ibrs_enabled)"
fi
echo "Powering off the guest!"
/sbin/reboot -f -p
